name: Run Selected Tests and Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests-and-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make setup.sh executable and run it
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: run unit tests
        run: |
          pytest -k "test_core.py" -v
          pytest -k "test_functions.py" -v

      - name: run examples
        run: |
          python -c gtfs_railways/gtfs_railways/examples/example_01.py
          python -c gtfs_railways/gtfs_railways/examples/example_02.py
          python -c gtfs_railways/gtfs_railways/examples/example_03.py
          python -c gtfs_railways/gtfs_railways/examples/example_04.py
          python -c gtfs_railways/gtfs_railways/examples/example_05.py
